import type { Metadata } from "next";
import "./globals.css";
import { css } from "../../styled-system/css";
import Provider from "../components/provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={css({
          backgroundColor: "#2c2c2c",
        })}
      >
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
